trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

stages:
  - stage: Build
    displayName: 'Build Microfront App'
    jobs:
      - job: Build
        displayName: 'Build Microfront Application'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Install Node.js'

          - script: |
              npm install
              npm run build:microfrontend-app
            displayName: 'Build Microfront Application'

          - task: PublishPipelineArtifact@1
            inputs:
              artifactName: 'microfrontend-app'
              path: 'dist/microfrontend-app'
            displayName: 'Publish Microfront App Build Artifact'

  - stage: Deploy
    displayName: 'Deploy Microfront App'
    dependsOn: Build
    jobs:
      - deployment: DeployMicrofront
        displayName: 'Deploy Microfront App to Azure'
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: 'Azure subscription 1'
                    appName: 'microfrontend-app'
                    package: '$(Pipeline.Workspace)/microfrontend-app'
                    deployToSlotOrASE: true
                    resourceGroupName: 'Fiap'
                    slotName: 'Production'
                    connectedServiceName: 'Azure subscription 1'